### ISSUE TITLE
PRACTICA TEST CASE - PC BOX

### ISSUE THREAD

**Issue by MaGuadalupeQuiroz** [SistemasTecTlaxiaco/practica-de-test-case-entrevista-gestion-de-proyecto#2]
[PRACTICA TEST CASE PC BOX.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-test-case-entrevista-gestion-de-proyecto/files/7323158/PRACTICA.TEST.CASE.PC.BOX.pdf)

**Comment by Nancy2050** [comment]
PUNTAJE: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
